# Change these first
owner: BBVA-Openweb # Your GitHub organization or username, where this repository lives
repo: openweb-uptime-sites # The name of this repository

sites:
  - name: Panel de Openweb
    url: https://webpublicas.bbva.com/
  - name: Accionistas e Inversores (es)
    url: https://accionistaseinversores.bbva.com/
  - name: Accionistas e Inversores (en)
    url: https://shareholdersandinvestors.bbva.com/
  - name: BBVA IT Spain
    url: 	https://www.bbvaitspain.com
  - name: BBVA.com
    url: https://www.bbva.com
  - name: Fundación BBVA
    url: https://www.fbbva.es/
  - name: OpenMind
    url: https://www.bbvaopenmind.com/
  - name: Research
    url: https://www.bbvaresearch.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: uptime-sites.openweb.bbva
  baseUrl: /openweb-uptime-sites
  logoUrl: https://cdn.openweb.bbva/logos/openweb/small.png
  favicon: https://cdn.openweb.bbva/favicon/bbva/favicon-96x96.png
  name: Openweb Sites - Upptime
  introTitle: "**Openweb Sites** is the uptime monitor and status page."
  introMessage: This is a status page which uses _real-time_ data (every site is checked every 5 minutes). You can check the response time of every monitored site.
  themeUrl: https://cdn.openweb.bbva/css/status/openweb-theme.css
  navbar:
    - title: Openweb
      href: https://webpublicas.bbva.com/
  metaTags:
    - name: "robots"
      content: "noindex"
  robotsText: "User-agent: * \n Disallow: /"


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
